name: universal_web
version: 2.0.0-wip
description: Wrapper around package:web that adds compatibility for non-web environments.
repository: https://github.com/schultek/universal_web

environment:
  sdk: ^3.4.0

dependencies:
  web: 2.0.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  path: ^1.8.3
  test: ^1.24.4

dependency_overrides:
  web:
    git:
      url: https://github.com/dart-lang/web
      path: web
      # Matches ../third_party/dart-sdk/sdk/DEPS `web_rev`.
      ref: 48b75126e511e2d3de65130f2e7aa21cca58f473
